services:
  - type: web
    name: musicapp
    env: python
    plan: free
    buildCommand: |
      pip install -r MusicApp/requirements.txt
      python MusicApp/manage.py collectstatic --noinput
      python MusicApp/manage.py migrate --noinput
    startCommand: gunicorn MusicApp.wsgi:application --access-logfile - --error-logfile - --log-level info
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHONUNBUFFERED
        value: "1"

